### ISSUE TITLE
[bug] FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dar1ock** [xforce/eve-echoes-tools#16]
Hi, i try to run docker img, but always stoped on one place, can't understand what's wrong

docker run -v$(pwd):/home/root/ cookiemagic/evee-tools dump_static /home/root/eve.xapk /home/root/staticdata 

/home/root/eve.xapk
/home/root/staticdata
/opt/eve-echoes-tools /opt/eve-echoes-tools
Traceback (most recent call last):
  File "scripts/dump_static_data.py", line 510, in <module>
    dump_static_data_fsd(xapk_temp_dir)
  File "scripts/dump_static_data.py", line 318, in dump_static_data_fsd
    for filename in os.listdir(obb_path):
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpqld7cygx/Android/obb/com.netease.eve.en'
/opt/eve-echoes-tools

**Comment by dar1ock** [comment]
Try to use docker on clean VM systems Ubuntu 20 lts, debian 9/10...
Same result on all of it's

can any body help? what am'i doing wrong? 
when run docker i see cpu/hdd activity about 1-2 minutes, then error

**Comment by xforce** [comment]
Where did you get the xapk from? It looks like it is built a bit differently than the ones I used so it doesn't find something it expects to be there.

**Comment by dar1ock** [comment]
sorry for late answer
from the virtual machine when installing the application
