### ISSUE TITLE
docker build fail

### ISSUE THREAD

**Issue by GodDai** [xforce/eve-echoes-tools#17]
run  ./build.sh 
`
[+] Building 144.7s (16/25)
 => [internal] load build definition from Dockerfile                                                                                            0.0s
 => => transferring dockerfile: 1.17kB                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                               0.0s
 => => transferring context: 34B                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/alpine:edge                                                                                  3.1s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                                   0.0s
 => CACHED https://api.github.com/repos/xforce/eve-echoes-tools/compare/main...HEAD                                                             0.0s
 => [internal] load build context                                                                                                               0.2s
 => => transferring context: 177.72kB                                                                                                           0.1s
 => CACHED [cargo-build  1/10] FROM docker.io/library/alpine:edge@sha256:2f77b6664f181b246244f9cd052155e74fb3f26d2a502edecd5fff0fc4bda388       0.0s
 => CACHED [cargo-build  2/10] RUN apk add -X http://dl-cdn.alpinelinux.org/alpine/edge/testing rust cargo                                      0.0s
 => CACHED [cargo-build  3/10] WORKDIR /app                                                                                                     0.0s
 => CACHED [cargo-build  4/10] ADD Cargo.toml Cargo.toml                                                                                        0.0s
 => CACHED [cargo-build  5/10] ADD fsd2json/src /app/fsd2json/src                                                                               0.0s
 => CACHED [cargo-build  6/10] ADD fsd2json/Cargo.toml /app/fsd2json/Cargo.toml                                                                 0.0s
 => CACHED [cargo-build  7/10] ADD neox-tools/src /app/neox-tools/src                                                                           0.0s
 => CACHED [cargo-build  8/10] ADD neox-tools/Cargo.toml /app/neox-tools/Cargo.toml                                                             0.0s
 => CACHED [cargo-build  9/10] RUN cargo install --path fsd2json --root /usr/local/                                                             0.0s
 => ERROR [cargo-build 10/10] RUN cargo install --path neox-tools --root /usr/local/                                                          141.3s
------
 > [cargo-build 10/10] RUN cargo install --path neox-tools --root /usr/local/:
#15 0.341   Installing npktool v0.1.0 (/app/neox-tools)
#15 0.473     Updating crates.io index
#15 2.798  Downloading crates ...
#15 4.281   Downloaded memchr v1.0.2
#15 4.327   Downloaded murmur3 v0.5.1
#15 4.415   Downloaded num-bigint v0.3.2
#15 4.550   Downloaded memchr v2.4.0
#15 4.591   Downloaded nom v3.2.1
#15 4.603   Downloaded num-iter v0.1.42
#15 4.622   Downloaded ppv-lite86 v0.2.10
#15 4.638   Downloaded rand_chacha v0.2.2
#15 4.656   Downloaded rand_core v0.5.1
#15 4.668   Downloaded terminal_size v0.1.17
#15 4.678   Downloaded scopeguard v1.1.0
#15 4.701   Downloaded smallvec v1.6.1
#15 4.738   Downloaded tree_magic v0.2.3
#15 4.745   Downloaded cfg-if v0.1.10
#15 4.759   Downloaded fixedbitset v0.2.0
#15 4.773   Downloaded lock_api v0.3.4
#15 4.806   Downloaded indicatif v0.16.2
#15 4.828   Downloaded num-rational v0.3.2
#15 4.860   Downloaded parking_lot_core v0.7.2
#15 4.864   Downloaded fnv v1.0.7
#15 4.871   Downloaded number_prefix v0.4.0
#15 4.892   Downloaded getrandom v0.1.16
#15 4.927   Downloaded parking_lot v0.10.2
#15 5.119   Downloaded petgraph v0.5.1
#15 5.163   Downloaded rand v0.7.3
#15 5.423   Downloaded regex-syntax v0.6.25
#15 5.445   Downloaded num-complex v0.3.1
#15 5.638   Downloaded regex v1.5.4
#15 5.671   Downloaded console v0.14.1
#15 11.53   Downloaded compress v0.2.1
#15 11.63   Downloaded num v0.3.1
#15 11.64   Downloaded aho-corasick v0.7.18
#15 11.66    Compiling libc v0.2.98
#15 11.66    Compiling getrandom v0.1.16
#15 11.99    Compiling memchr v2.4.0
#15 12.25    Compiling scopeguard v1.1.0
#15 12.35    Compiling cfg-if v0.1.10
#15 12.39    Compiling smallvec v1.6.1
#15 12.41    Compiling ppv-lite86 v0.2.10
#15 12.81    Compiling fixedbitset v0.2.0
#15 13.06    Compiling regex-syntax v0.6.25
#15 14.08    Compiling number_prefix v0.4.0
#15 14.36    Compiling fnv v1.0.7
#15 14.45    Compiling murmur3 v0.5.1
#15 14.62    Compiling num-traits v0.2.14
#15 14.84    Compiling num-integer v0.1.44
#15 15.06    Compiling num-bigint v0.3.2
#15 15.53    Compiling num-rational v0.3.2
#15 15.75    Compiling num-iter v0.1.42
#15 15.99    Compiling lock_api v0.3.4
#15 25.00    Compiling atty v0.2.14
#15 25.11    Compiling time v0.1.44
#15 28.59    Compiling terminal_size v0.1.17
#15 28.79    Compiling memchr v1.0.2
#15 29.10    Compiling parking_lot_core v0.7.2
#15 30.33    Compiling aho-corasick v0.7.18
#15 40.82    Compiling num-complex v0.3.1
#15 41.61    Compiling petgraph v0.5.1
#15 42.25    Compiling rand_core v0.5.1
#15 42.96    Compiling colored v1.9.3
#15 44.81    Compiling console v0.14.1
#15 45.36    Compiling nom v3.2.1
#15 49.94    Compiling parking_lot v0.10.2
#15 50.58    Compiling regex v1.5.4
#15 65.71    Compiling chrono v0.4.19
#15 73.76    Compiling rand_chacha v0.2.2
#15 75.86    Compiling tree_magic v0.2.3
#15 89.60    Compiling indicatif v0.16.2
#15 94.75    Compiling simple_logger v1.13.0
#15 97.00    Compiling rand v0.7.3
#15 101.1    Compiling num v0.3.1
#15 101.2    Compiling clap v3.0.0-beta.2
#15 104.1    Compiling compress v0.2.1
#15 141.0    Compiling npktool v0.1.0 (/app/neox-tools)
#15 141.3 error[E0716]: temporary value dropped while borrowed
#15 141.3    --> neox-tools/src/main.rs:688:37
#15 141.3     |
#15 141.3 688 |                     pb.set_message(&format!("{}", file_name));
#15 141.3     |                     ----------------^^^^^^^^^^^^^^^^^^^^^^^^-- temporary value is freed at the end of this statement
#15 141.3     |                     |               |
#15 141.3     |                     |               creates a temporary which is freed while still in use
#15 141.3     |                     argument requires that borrow lasts for `'static`
#15 141.3     |
#15 141.3     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
#15 141.3
#15 141.3 error: aborting due to previous error
#15 141.3
#15 141.3 For more information about this error, try `rustc --explain E0716`.
#15 141.3 error: failed to compile `npktool v0.1.0 (/app/neox-tools)`, intermediate artifacts can be found at `/app/target`
#15 141.3
#15 141.3 Caused by:
#15 141.3   could not compile `npktool`
#15 141.3
#15 141.3 To learn more, run the command again with --verbose.
------
executor failed running [/bin/sh -c cargo install --path neox-tools --root /usr/local/]: exit code: 101
`
macos 10.15.7
docker  Server version 20.10.7

**Comment by GodDai** [comment]
run `docker run -v$(pwd):/data cookiemagic/evee-tools dump_static /data/eve.xapk /data/staticdata`
```
/data/eve.xapk
/data/staticdata
/opt/eve-echoes-tools /opt/eve-echoes-tools
Traceback (most recent call last):
  File "scripts/dump_static_data.py", line 510, in <module>
    dump_static_data_fsd(xapk_temp_dir)
  File "scripts/dump_static_data.py", line 318, in dump_static_data_fsd
    for filename in os.listdir(obb_path):
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpq54wc_6s/Android/obb/com.netease.eve.en'
/opt/eve-echoes-tools
```

eve version from [china version](https://g85.gdl.netease.com/g85_3.2.3_release20210730_126171_netease_cn_zh_cn_release_netease.apk)

**Comment by GodDai** [comment]
and next run in container:

run `docker run -v$(pwd):/data --entrypoint sh cookiemagic/evee-tools`

```
/opt/eve-echoes-tools # cd ..
/opt # ./cmd.sh dump_static /data/eve.xapk /data/staticdata

/data/eve.xapk
/data/staticdata
/opt/eve-echoes-tools /opt
Traceback (most recent call last):
  File "scripts/dump_static_data.py", line 510, in <module>
    dump_static_data_fsd(xapk_temp_dir)
  File "scripts/dump_static_data.py", line 318, in dump_static_data_fsd
    for filename in os.listdir(obb_path):
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpcrrzojws/Android/obb/com.netease.eve.en'
/opt
/opt # cd /tmp/tmpcrrzojws/
sh: cd: can't cd to /tmp/tmpcrrzojws/: No such file or directory
/opt # cd /tmp
/tmp # ls
/tmp #
```

The tmp directory is empty.

**Comment by SilkyPantsDan** [comment]
There should be a space between `-v` and `$(pwd)` shouldn't there?

```run docker run -v $(pwd):/data cookiemagic/evee-tools dump_static /data/eve.xapk /data/staticdata```

**Comment by GodDai** [comment]
> There should be a space between `-v` and `$(pwd)` shouldn't there?
> 
> `run docker run -v $(pwd):/data cookiemagic/evee-tools dump_static /data/eve.xapk /data/staticdata`

 add  a space 
`docker run -v $(pwd):/data cookiemagic/evee-tools dump_static /data/eve.xapk /data/staticdata`
```
/data/eve.xapk
/data/staticdata
/opt/eve-echoes-tools /opt/eve-echoes-tools
Traceback (most recent call last):
  File "scripts/dump_static_data.py", line 510, in <module>
    dump_static_data_fsd(xapk_temp_dir)
  File "scripts/dump_static_data.py", line 318, in dump_static_data_fsd
    for filename in os.listdir(obb_path):
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmppftqgut6/Android/obb/com.netease.eve.en'
/opt/eve-echoes-tools
```
Still the same

**Comment by GodDai** [comment]
but i'm run this command in container is work: `npktool x res0.npk res1.npk res2.npk res3.npk res4.npk res5.npk res6.npk res7.npk res8.npk res9.npk res10.npk res11.npk res12.npk`
the command help me unpack some resource files which filename end with '.npk'

**Comment by SilkyPantsDan** [comment]
Ahh - I missed seeing this comment: https://github.com/xforce/eve-echoes-tools/issues/17#issuecomment-894964040

It's looking for the English OBB data, which would be in the XAPK that you can get from other dump sites. The link you have given seems to be for an APK which is packaged differently.

I have a [PR](https://github.com/xforce/eve-echoes-tools/pull/14) that might help, as you do not need to perform the OBB extraction step with your APK (as it does not exist) and need to skip to the processing step I think
